### PR TITLE
Update favicons

### PR DESCRIPTION
**Pull request by i-like-robots**
As requested

### CODE REVIEW

**Comment by matthew-andrews** [comment]
👎 read the readme:-
https://github.com/Financial-Times/next-assets/#next-assets-

**Comment by bjfletcher** [comment]
How'll you bust the cache?

**Comment by i-like-robots** [comment]
Boo and hiss! _final_final.png I reckon

**Comment by matthew-andrews** [comment]
_2016_onwards.png

**Comment by matthew-andrews** [comment]
also, @bjfletcher snap 😄

**Comment by i-like-robots** [comment]
OK sorted and also https://github.com/Financial-Times/next-assets/pull/101

**Comment by bjfletcher** [comment]
https://github.com/Financial-Times/next-assets/blob/master/public-src/manifest/manifest-v3.json ?

**Comment by i-like-robots** [comment]
@bjfletcher Have created -v4

**Comment by bjfletcher** [comment]
:+1: Thanks Matt :tada:

**Pull request merged**
