### PR TITLE
updated amex

### PR DESCRIPTION
**Pull request by ifyio**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
just fyi the cache times on this repo are quite long (6 months i think)…  to reliably update it's better to create new images rather than replace…

https://github.com/Financial-Times/next-assets/blob/master/README.md

**Comment by ifyio** [comment]
Thanks for the heads up @matthew-andrews. I'm however able to successfully access the updated image from the app (not live yet) and the web https://next-geebee.ft.com/assets/ccards/amex.png. Is this still an issue?

**Comment by matthew-andrews** [comment]
the thing is it's not guaranteed.  the fact it's not live yet will help because people in different regions will see different versions so at the moment there should be less chance that this image has been cached by those nodes in far flung locations.  i think in this case it's probably not the end of the world if a tiny minority of people see the old one.  just fyi for the future :)

btw. the cache time is 364 days, not 6 months.

**Comment by ifyio** [comment]
got it. thanks.

**Pull request merged**
