### PR TITLE
Adding the product images that would go on the premium barrier

### PR DESCRIPTION
**Pull request by ifyio**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
public-src/product/product-images.psd

psd?

**Comment by ifyio** [comment]
Oops

**Comment by ifyio** [comment]
Cheers @matthew-andrews. Am I good to go with this?

**Comment by matthew-andrews** [comment]
:ship:

**Comment by matthew-andrews** [comment]
[they're quite small images — do we have 2x versions?]

**Comment by matthew-andrews** [comment]
unless they're really small these are going to look a bit crumby on retina, but if that's ok, then yep ship ship ship

**Comment by ifyio** [comment]
Yeah they are indeed small. Will bring up the size with @SarahHornsey when she get's back. For now, I will merge these in so that I can used them to test what I'm working on.

**Pull request merged**
